{
 "title": "Netology GorelovNN",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Количество места на файловой системе",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "Утилизация CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Количество свободной оперативной памяти;",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes" }
   ]
  },
  {
   "title": "CPU Load Average 1/5/15:",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1" },
    { "expr": "node_load5" },
    { "expr": "node_load15" }
   ]
  }
 ]
}